/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

		import org.br.sisgom.bean.Endereco;
		import org.br.sisgom.bean.Contato;
		import org.br.sisgom.bean.Veiculo;

// Start of user code for imports

// End of user code

public  class Cliente extends PessoaBase {
	/**
	 * The documentation of the attribute veiculo.
	 * 
	 * @generated
	 */
	private Veiculo veiculo;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Cliente() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getVeiculo.
	 * 
	 * @generated
	 */
	public Veiculo getVeiculo() {
		return this.veiculo;
	}
	
	/**
	 * The documentation of the setter setVeiculo.
	 * 
	 * @generated
	 */
	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}
	
}
