/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;


// Start of user code for imports

// End of user code

public  class Endereco {
	/**
	 * The documentation of the attribute id.
	 * 
	 * @generated
	 */
	private Integer id;
	
	/**
	 * The documentation of the attribute cEP.
	 * 
	 * @generated
	 */
	private String cEP;
	
	/**
	 * The documentation of the attribute rua.
	 * 
	 * @generated
	 */
	private String rua;
	
	/**
	 * The documentation of the attribute estado.
	 * 
	 * @generated
	 */
	private String estado;
	
	/**
	 * The documentation of the attribute cidade.
	 * 
	 * @generated
	 */
	private String cidade;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Endereco() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getId.
	 * 
	 * @generated
	 */
	public Integer getId() {
		return this.id;
	}
	
	/**
	 * The documentation of the setter setId.
	 * 
	 * @generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * The documentation of the getter getCEP.
	 * 
	 * @generated
	 */
	public String getCEP() {
		return this.cEP;
	}
	
	/**
	 * The documentation of the setter setCEP.
	 * 
	 * @generated
	 */
	public void setCEP(String cEP) {
		this.cEP = cEP;
	}
	/**
	 * The documentation of the getter getRua.
	 * 
	 * @generated
	 */
	public String getRua() {
		return this.rua;
	}
	
	/**
	 * The documentation of the setter setRua.
	 * 
	 * @generated
	 */
	public void setRua(String rua) {
		this.rua = rua;
	}
	/**
	 * The documentation of the getter getEstado.
	 * 
	 * @generated
	 */
	public String getEstado() {
		return this.estado;
	}
	
	/**
	 * The documentation of the setter setEstado.
	 * 
	 * @generated
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}
	/**
	 * The documentation of the getter getCidade.
	 * 
	 * @generated
	 */
	public String getCidade() {
		return this.cidade;
	}
	
	/**
	 * The documentation of the setter setCidade.
	 * 
	 * @generated
	 */
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}
	
}
