/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;


// Start of user code for imports

// End of user code

public  class ItensDeServico {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public ItensDeServico() {
		super();
	}
	


}
