/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;


// Start of user code for imports

// End of user code

public  class Servico {
	/**
	 * The documentation of the attribute nome.
	 * 
	 * @generated
	 */
	private String nome;
	
	/**
	 * The documentation of the attribute valor.
	 * 
	 * @generated
	 */
	private Float valor;
	
	/**
	 * The documentation of the attribute codigo.
	 * 
	 * @generated
	 */
	private Integer codigo;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Servico() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getNome.
	 * 
	 * @generated
	 */
	public String getNome() {
		return this.nome;
	}
	
	/**
	 * The documentation of the setter setNome.
	 * 
	 * @generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}
	/**
	 * The documentation of the getter getValor.
	 * 
	 * @generated
	 */
	public Float getValor() {
		return this.valor;
	}
	
	/**
	 * The documentation of the setter setValor.
	 * 
	 * @generated
	 */
	public void setValor(Float valor) {
		this.valor = valor;
	}
	/**
	 * The documentation of the getter getCodigo.
	 * 
	 * @generated
	 */
	public Integer getCodigo() {
		return this.codigo;
	}
	
	/**
	 * The documentation of the setter setCodigo.
	 * 
	 * @generated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	
}
