/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.entities;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

// Start of user code for imports
// End of user code
@Entity
@Table(name = "Cliente")
@PrimaryKeyJoinColumn(name = "Id")
public class ClienteEntity extends PessoaBaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5851383994789305093L;
	
	@OneToMany(mappedBy="cliente")
	private List<VeiculoEntitty> veiculo;

	private int codigoCliente;

	public int getCodigoCliente() {
		return codigoCliente;
	}

	public void setCodigoCliente(int codigoCliente) {
		this.codigoCliente = codigoCliente;
	}

	public ClienteEntity() {
		super();
	}

	public ClienteEntity(List<ContatoEntity> contatos,
			List<EnderecoEntity> enderecos, String nome, String cPFouCNPJ,
			int codigoCliente) {
		super(contatos, enderecos, nome, cPFouCNPJ);
		this.codigoCliente = codigoCliente;
	}

	public List<VeiculoEntitty> getVeiculo() {
		return this.veiculo;
	}

	public void setVeiculo(List<VeiculoEntitty> veiculo) {
		this.veiculo = veiculo;
	}

}
