/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.eclipse.acceleo.sisgom.uml2java.utils.BaseBean;

// Start of user code for imports
// End of user code
@Entity
@Table(name="Contato")
public  class ContatoEntity extends BaseBean {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6975855890023023478L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	private String email;
	
	private String telefone;
	
	public ContatoEntity(String email, String telefone) {
		super();
		this.email = email;
		this.telefone = telefone;
	}
	
	public ContatoEntity() {
		super();
	}
	
	
	public String getEmail() {
		return this.email;
	}
	
	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getTelefone() {
		return this.telefone;
	}
	
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
}
