/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

// Start of user code for imports
// End of user code
@Entity
@Table(name="Endereco")
public  class EnderecoEntity {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	
	private String rua;
	
	private String cidade;
	
	private String estado;
	
	private String bairro;
	
	private String cEP;
	
	private int numero;
	
	public EnderecoEntity(String rua, String cidade, String estado, int numero, String cep, String bairro) {
		super();
		this.rua = rua;
		this.cidade = cidade;
		this.estado = estado;
		this.bairro = bairro;
		this.cEP = cep;
		this.numero = numero;
	}
	
	public EnderecoEntity() {
		super();
	}
	
	public int getId() {
		return this.id;
	}
	
	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getcEP() {
		return cEP;
	}

	public void setcEP(String cEP) {
		this.cEP = cEP;
	}

	public int getNumero() {
		return numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public String getRua() {
		return this.rua;
	}
	
	public void setRua(String rua) {
		this.rua = rua;
	}
	
	public String getCidade() {
		return this.cidade;
	}
	
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getCEP() {
		return this.cEP;
	}

	public void setCEP(String cEP) {
		this.cEP = cEP;
	}
	
}
