/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.entities;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.PrimaryKeyJoinColumn;

// Start of user code for imports
// End of user code
@Entity
@Table(name="Funcionario")
@PrimaryKeyJoinColumn(name="Id")
public  class FuncionarioEntity extends PessoaBaseEntity {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3266088180726513949L;
	private int codigoFuncionario;
	
	public FuncionarioEntity() {
		super();
	}

	public FuncionarioEntity(List<ContatoEntity> contatos, List<EnderecoEntity> enderecos, String nome, String cPFouCNPJ, int codigoFuncionario){
		super(contatos, enderecos, nome, cPFouCNPJ);
		this.codigoFuncionario = codigoFuncionario;
	}
	
	public int getCodigoFuncionario() {
		return this.codigoFuncionario;
	}
	
	public void setCodigoFuncionario(int codigoFuncionario) {
		this.codigoFuncionario = codigoFuncionario;
	}
	
}
