/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.entities;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.eclipse.acceleo.sisgom.uml2java.utils.BaseBean;

@Entity
@Table(name = "OrdemDeServico")
public  class OrdemDeServicoEntity extends BaseBean {
	private static final long serialVersionUID = 5187766943714194024L;

	@ManyToMany
    @JoinTable(name="ItensDeMercadoria", joinColumns={@JoinColumn(name="OrdemDeServico_Codigo")}, inverseJoinColumns={@JoinColumn(name="Mercadoria_Codigo")})
	private List<MercadoriaEntity> mercadorias;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int codigo;
	@Temporal(value = TemporalType.TIMESTAMP)
	private Date dataEntradaVeiculo;
	@ManyToOne
	@JoinColumn(name="Veiculo_Id", nullable = false)
	private VeiculoEntitty veiculo;
	@ManyToMany
    @JoinTable(name="ItensDeServico", joinColumns={@JoinColumn(name="OrdemDeServico_Codigo")}, inverseJoinColumns={@JoinColumn(name="Servico_Codigo")})
	private List<ServicoEntity> servicos;
	
	public OrdemDeServicoEntity() {
		super();
	}
	
	public List<MercadoriaEntity> getMercadorias() {
		return this.mercadorias;
	}
	
	public void setMercadorias(List<MercadoriaEntity> mercadorias) {
		this.mercadorias = mercadorias;
	}
	
	public void setMercadorias(MercadoriaEntity mercadorias) {
		if(this.mercadorias == null)
			this.mercadorias = new ArrayList<MercadoriaEntity>();
		this.mercadorias.add(mercadorias);
	}
	
	public int getCodigo() {
		return this.codigo;
	}
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
	
	public Date getDataEntradaVeiculo() {
		return this.dataEntradaVeiculo;
	}
	
	public void setDataEntradaVeiculo(Date dataEntradaVeiculo) {
		this.dataEntradaVeiculo = dataEntradaVeiculo;
	}
	
	public VeiculoEntitty getVeiculo() {
		return this.veiculo;
	}
	
	public void setVeiculo(VeiculoEntitty veiculo) {
		this.veiculo = veiculo;
	}
	
	public List<ServicoEntity> getServicos() {
		return this.servicos;
	}
	
	public void setServicos(List<ServicoEntity> servicos) {
		this.servicos = servicos;
	}
	
	public void setServicos(ServicoEntity servicos) {
		if (this.servicos == null) {
			this.servicos = new ArrayList<ServicoEntity>();
		}
		
		this.servicos.add(servicos);
	}
}
