/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.dao;

	import org.br.sisgom.bean.Veiculo;
	import org.br.sisgom.bean.Peca;
	

// Start of user code for imports

// End of user code

public  class PecaDAOImpl implements PecaDAO {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public PecaDAOImpl() {
		super();
	}
	
	/**
	 * The documentation of the method alterar.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void alterar(Peca entidade) {
		// Start of user code for the body of alterar
		// TODO should be implemented
		// End of user code
	}
	
	/**
	 * The documentation of the method inserir.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void inserir(Peca entidade) {
		// Start of user code for the body of inserir
		// TODO should be implemented
		// End of user code
	}
	
	/**
	 * The documentation of the method deletar.
	 * 
	 * @param codigo
	 * 
	 * @generated
	 */
	public void deletar(Integer codigo) {
		// Start of user code for the body of deletar
		// TODO should be implemented
		// End of user code
	}
	
	/**
	 * The documentation of the method obter.
	 * 
	 * @param codigo
	 * @return
	 * 
	 * @generated
	 */
	public Veiculo obter(Integer codigo) {
		// Start of user code for the body of obter
		// TODO should be implemented
		return null;
		// End of user code
	}
	
	
	
}
