<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sisgom" nsURI="http://www.example.org/projeto_teste" nsPrefix="sisgom">
  <eSubpackages name="bean" nsURI="bean" nsPrefix="bean">
    <eClassifiers xsi:type="ecore:EClass" name="PessoaBase" abstract="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="simple"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
          iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Nome da pessoa"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="CPFouCNPJ" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Numero do CPF ou do CNPJ"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Contatos" upperBound="-1"
          eType="#//bean/Contato" containment="true" eKeys="#//bean/Contato/Id"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Enderecos" upperBound="-1"
          eType="#//bean/Endereco" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Endereco">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rua" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Estado" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cidade" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="CEP" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fornecedor" eSuperTypes="#//bean/PessoaBase">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="InscricaoEstadual" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Funcionario" eSuperTypes="#//bean/PessoaBase">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Matricula" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Cliente" eSuperTypes="#//bean/PessoaBase">
      <eStructuralFeatures xsi:type="ecore:EReference" name="veiculo" upperBound="-1"
          eType="#//bean/Veiculo" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Contato">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Informações de contato"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
          iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Identificador Contato"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Telefone" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Telefone de contato"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Email" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="E-mail de contato"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Servico">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Valor" ordered="false"
          unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="TipoCobranca">
      <eLiterals name="PorHora"/>
      <eLiterals name="PorUnidade" value="1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrdemDeServico">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="DataEntradaVeiculo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//DateTime"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Veiculo" lowerBound="1"
          eType="#//bean/Veiculo" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ItensDeServico" lowerBound="1"
          upperBound="-1" eType="#//bean/ItensDeServico"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Peca">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Codigo" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Nome" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValorCompra" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValorVenda" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Fornecedor" lowerBound="1"
          eType="#//bean/Fornecedor"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Veiculo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Chassis" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Modelo" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Ano" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cor" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ItensDeServico">
      <eStructuralFeatures xsi:type="ecore:EReference" name="Funcionario" lowerBound="1"
          eType="#//bean/Funcionario"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="servico" lowerBound="1"
          eType="#//bean/Servico"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="peca" lowerBound="1"
          eType="#//bean/Peca"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValorServico" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ValorPeca" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Float"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
