/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.dao;

import org.br.sisgom.bean.OrdemDeServico;
// Start of user code for imports
// End of user code

/**
 * The documentation of the interface OrdenDeServicoDAO.
 * 
 * @generated
 */
public interface OrdenDeServicoDAO {
	/**
	 * The documentation of the method inserir.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void Inserir(OrdemDeServico entidade);
	
	/**
	 * The documentation of the method alterar.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void Alterar(OrdemDeServico entidade);
	
	/**
	 * The documentation of the method deletar.
	 * 
	 * @param codigo
	 * 
	 * @generated
	 */
	public void Deletar(Integer codigo);
	
	/**
	 * The documentation of the method obter.
	 * 
	 * @param codigo
	 * @return
	 * 
	 * @generated
	 */
	public OrdemDeServico Obter(Integer codigo);
	
}
