/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.dao;

import org.br.sisgom.bean.Servico;
	
// Start of user code for imports
// End of user code

public  class ServicoDAOImpl implements ServicoDAO {
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public ServicoDAOImpl() {
    super();
  }
	
	/**
	 * The documentation of the method inserir.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void Inserir(Servico entidade) {
    // Start of user code for the body of inserir
    // TODO should be implemented
    // End of user code
  }
	
	/**
	 * The documentation of the method alterar.
	 * 
	 * @param entidade
	 * 
	 * @generated
	 */
	public void Alterar(Servico entidade) {
    // Start of user code for the body of alterar
    // TODO should be implemented
    // End of user code
  }
	
	/**
	 * The documentation of the method deletar.
	 * 
	 * @param codigo
	 * 
	 * @generated
	 */
	public void Deletar(Integer codigo) {
    // Start of user code for the body of deletar
    // TODO should be implemented
    // End of user code
  }
	
	/**
	 * The documentation of the method obter.
	 * 
	 * @param codigo
	 * @return
	 * 
	 * @generated
	 */
	public Servico Obter(Integer codigo) {
    // Start of user code for the body of obter
    // TODO should be implemented
    return null;
    // End of user code
  }
	
	
	
}
