/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

// Start of user code for imports
// End of user code

public  class Endereco {
	private String estado;
	
	private String rua;
	
	private String cEP;
	
	private int id;
	
	private String cidade;
	
	public Endereco() {
		super();
	}
	
	
	public String getEstado() {
		return this.estado;
	}
	
	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	
	public String getRua() {
		return this.rua;
	}
	
	public void setRua(String rua) {
		this.rua = rua;
	}
	
	
	public String getCEP() {
		return this.cEP;
	}
	
	public void setCEP(String cEP) {
		this.cEP = cEP;
	}
	
	
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
	
	public String getCidade() {
		return this.cidade;
	}
	
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}
	
}
