/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

// Start of user code for imports
// End of user code

public  class Mercadoria {
	private float valorCompra;
	
	private float valorVenda;
	
	private int codigo;
	
	private String nome;
	
	public Mercadoria() {
		super();
	}
	
	
	public float getValorCompra() {
		return this.valorCompra;
	}
	
	public void setValorCompra(float valorCompra) {
		this.valorCompra = valorCompra;
	}
	
	
	public float getValorVenda() {
		return this.valorVenda;
	}
	
	public void setValorVenda(float valorVenda) {
		this.valorVenda = valorVenda;
	}
	
	
	public int getCodigo() {
		return this.codigo;
	}
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
	
	
	public String getNome() {
		return this.nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
}
