/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

import java.util.List;
	import java.util.Date;
	
// Start of user code for imports
// End of user code

public  class OrdemDeServico {
	private Veiculo veiculo;
	
	private List<Mercadoria> mercadorias;
	
	private List<Servico> servicos;
	
	private Date dataEntradaVeiculo;
	
	private int codigo;
	
	public OrdemDeServico() {
		super();
	}
	
	
	public Veiculo getVeiculo() {
		return this.veiculo;
	}
	
	public void setVeiculo(Veiculo veiculo) {
		this.veiculo = veiculo;
	}
	
	
	public List<Mercadoria> getMercadorias() {
		return this.mercadorias;
	}
	
	public void setMercadorias(List<Mercadoria> mercadorias) {
		this.mercadorias = mercadorias;
	}
	
	
	public List<Servico> getServicos() {
		return this.servicos;
	}
	
	public void setServicos(List<Servico> servicos) {
		this.servicos = servicos;
	}
	
	
	public Date getDataEntradaVeiculo() {
		return this.dataEntradaVeiculo;
	}
	
	public void setDataEntradaVeiculo(Date dataEntradaVeiculo) {
		this.dataEntradaVeiculo = dataEntradaVeiculo;
	}
	
	
	public int getCodigo() {
		return this.codigo;
	}
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
	
}
