/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

import java.util.List;
	
	
// Start of user code for imports
// End of user code

public abstract class PessoaBase {
	private String cPFouCNPJ;
	
	private List<Contato> contato;
	
	private String nome;
	
	private List<Endereco> endereco;
	
	private int id;
	
	public PessoaBase() {
		super();
	}
	
	
	public String getCPFouCNPJ() {
		return this.cPFouCNPJ;
	}
	
	public void setCPFouCNPJ(String cPFouCNPJ) {
		this.cPFouCNPJ = cPFouCNPJ;
	}
	
	
	public List<Contato> getContato() {
		return this.contato;
	}
	
	public void setContato(List<Contato> contato) {
		this.contato = contato;
	}
	
	
	public String getNome() {
		return this.nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	
	public List<Endereco> getEndereco() {
		return this.endereco;
	}
	
	public void setEndereco(List<Endereco> endereco) {
		this.endereco = endereco;
	}
	
	
	public int getId() {
		return this.id;
	}
	
	public void setId(int id) {
		this.id = id;
	}
	
}
