/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

// Start of user code for imports
// End of user code

public  class Servico {
	private String nome;
	
	private int codigo;
	
	private float valor;
	
	public Servico() {
		super();
	}
	
	
	public String getNome() {
		return this.nome;
	}
	
	public void setNome(String nome) {
		this.nome = nome;
	}
	
	
	public int getCodigo() {
		return this.codigo;
	}
	
	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}
	
	
	public float getValor() {
		return this.valor;
	}
	
	public void setValor(float valor) {
		this.valor = valor;
	}
	
}
