/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

// Start of user code for imports
// End of user code

public  class Veiculo {
	private String modelo;
	
	private String cor;
	
	private String chassis;
	
	private int ano;
	
	public Veiculo() {
		super();
	}
	
	
	public String getModelo() {
		return this.modelo;
	}
	
	public void setModelo(String modelo) {
		this.modelo = modelo;
	}
	
	
	public String getCor() {
		return this.cor;
	}
	
	public void setCor(String cor) {
		this.cor = cor;
	}
	
	
	public String getChassis() {
		return this.chassis;
	}
	
	public void setChassis(String chassis) {
		this.chassis = chassis;
	}
	
	
	public int getAno() {
		return this.ano;
	}
	
	public void setAno(int ano) {
		this.ano = ano;
	}
	
}
