/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.daos;

import org.eclipse.acceleo.sisgom.uml2java.entities.ClienteEntity;
import org.eclipse.acceleo.sisgom.uml2java.utils.GenericDao;

// Start of user code for imports
// End of user code

public  class ClienteDao extends GenericDao<ClienteEntity, Integer> {


}

