/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.daos;

import org.eclipse.acceleo.sisgom.uml2java.entities.ContatoEntity;
import org.eclipse.acceleo.sisgom.uml2java.utils.GenericDao;

// Start of user code for imports
// End of user code

public  class ContatoDao extends GenericDao<ContatoEntity, Integer> {


}