/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.eclipse.acceleo.sisgom.uml2java.daos;

import org.eclipse.acceleo.sisgom.uml2java.entities.OrdemDeServicoEntity;
import org.eclipse.acceleo.sisgom.uml2java.utils.GenericDao;

public  class OrdemDeServicoDao extends GenericDao<OrdemDeServicoEntity, Integer> {


}
