/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

	

// Start of user code for imports

// End of user code

public  class Contato {
	/**
	 * The documentation of the attribute id.
	 * 
	 * @generated
	 */
	private Integer id;
	
	/**
	 * The documentation of the attribute email.
	 * 
	 * @generated
	 */
	private String email;
	
	/**
	 * The documentation of the attribute telefone.
	 * 
	 * @generated
	 */
	private String telefone;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Contato() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getId.
	 * 
	 * @generated
	 */
	public Integer getId() {
		return this.id;
	}
	
	/**
	 * The documentation of the setter setId.
	 * 
	 * @generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * The documentation of the getter getEmail.
	 * 
	 * @generated
	 */
	public String getEmail() {
		return this.email;
	}
	
	/**
	 * The documentation of the setter setEmail.
	 * 
	 * @generated
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * The documentation of the getter getTelefone.
	 * 
	 * @generated
	 */
	public String getTelefone() {
		return this.telefone;
	}
	
	/**
	 * The documentation of the setter setTelefone.
	 * 
	 * @generated
	 */
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	
}
