/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

	

// Start of user code for imports

// End of user code

public  class Funciario extends PessoaBase {
	/**
	 * The documentation of the attribute codigoFuncionario.
	 * 
	 * @generated
	 */
	private Integer codigoFuncionario;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Funciario() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getCodigoFuncionario.
	 * 
	 * @generated
	 */
	public Integer getCodigoFuncionario() {
		return this.codigoFuncionario;
	}
	
	/**
	 * The documentation of the setter setCodigoFuncionario.
	 * 
	 * @generated
	 */
	public void setCodigoFuncionario(Integer codigoFuncionario) {
		this.codigoFuncionario = codigoFuncionario;
	}
	
}
