/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

	

// Start of user code for imports

// End of user code

public  class ItensDePeca {
	/**
	 * The documentation of the attribute peca.
	 * 
	 * @generated
	 */
	private Peca peca;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public ItensDePeca() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getPeca.
	 * 
	 * @generated
	 */
	public Peca getPeca() {
		return this.peca;
	}
	
	/**
	 * The documentation of the setter setPeca.
	 * 
	 * @generated
	 */
	public void setPeca(Peca peca) {
		this.peca = peca;
	}
	
}
