/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

	
// Start of user code for imports
// End of user code

public  class Peca {
	/**
	 * The documentation of the attribute nome.
	 * 
	 * @generated
	 */
	private String nome;
	
	/**
	 * The documentation of the attribute valorVenda.
	 * 
	 * @generated
	 */
	private float valorVenda;
	
	/**
	 * The documentation of the attribute valorCompra.
	 * 
	 * @generated
	 */
	private float valorCompra;
	
	/**
	 * The documentation of the attribute codigo.
	 * 
	 * @generated
	 */
	private int codigo;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Peca() {
    super();
  }
	
	
	/**
	 * The documentation of the getter getNome.
	 * 
	 * @generated
	 */
	
	public String getNome() {
    return this.nome;
  }
	
	/**
	 * The documentation of the setter setNome.
	 * 
	 * @generated
	 */
	public void setNome(String nome) {
    this.nome = nome;
  }
	/**
	 * The documentation of the getter getValorVenda.
	 * 
	 * @generated
	 */
	
	public float getValorVenda() {
    return this.valorVenda;
  }
	
	/**
	 * The documentation of the setter setValorVenda.
	 * 
	 * @generated
	 */
	public void setValorVenda(float valorVenda) {
    this.valorVenda = valorVenda;
  }
	/**
	 * The documentation of the getter getValorCompra.
	 * 
	 * @generated
	 */
	
	public float getValorCompra() {
    return this.valorCompra;
  }
	
	/**
	 * The documentation of the setter setValorCompra.
	 * 
	 * @generated
	 */
	public void setValorCompra(float valorCompra) {
    this.valorCompra = valorCompra;
  }
	/**
	 * The documentation of the getter getCodigo.
	 * 
	 * @generated
	 */
	
	public int getCodigo() {
    return this.codigo;
  }
	
	/**
	 * The documentation of the setter setCodigo.
	 * 
	 * @generated
	 */
	public void setCodigo(int codigo) {
    this.codigo = codigo;
  }
	
}
