/**
 * Generated by Acceleo 3
 * All rights reserved.
 */
package org.br.sisgom.bean;

	

// Start of user code for imports

// End of user code

public  class Peca {
	/**
	 * The documentation of the attribute valorCompra.
	 * 
	 * @generated
	 */
	private Float valorCompra;
	
	/**
	 * The documentation of the attribute valorVenda.
	 * 
	 * @generated
	 */
	private Float valorVenda;
	
	/**
	 * The documentation of the attribute nome.
	 * 
	 * @generated
	 */
	private String nome;
	
	/**
	 * The documentation of the attribute codigo.
	 * 
	 * @generated
	 */
	private Integer codigo;
	
	
	/**
	 * The documentation of the constructor.
	 * 
	 * @generated
	 */
	public Peca() {
		super();
	}
	
	
	/**
	 * The documentation of the getter getValorCompra.
	 * 
	 * @generated
	 */
	public Float getValorCompra() {
		return this.valorCompra;
	}
	
	/**
	 * The documentation of the setter setValorCompra.
	 * 
	 * @generated
	 */
	public void setValorCompra(Float valorCompra) {
		this.valorCompra = valorCompra;
	}
	/**
	 * The documentation of the getter getValorVenda.
	 * 
	 * @generated
	 */
	public Float getValorVenda() {
		return this.valorVenda;
	}
	
	/**
	 * The documentation of the setter setValorVenda.
	 * 
	 * @generated
	 */
	public void setValorVenda(Float valorVenda) {
		this.valorVenda = valorVenda;
	}
	/**
	 * The documentation of the getter getNome.
	 * 
	 * @generated
	 */
	public String getNome() {
		return this.nome;
	}
	
	/**
	 * The documentation of the setter setNome.
	 * 
	 * @generated
	 */
	public void setNome(String nome) {
		this.nome = nome;
	}
	/**
	 * The documentation of the getter getCodigo.
	 * 
	 * @generated
	 */
	public Integer getCodigo() {
		return this.codigo;
	}
	
	/**
	 * The documentation of the setter setCodigo.
	 * 
	 * @generated
	 */
	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}
	
}
